server:
  port: 9527

spring:
  application:
    name: mircoservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

zuul:
  prefix: /chen
  #ignored-services: microservicecloud-dept 禁止一个  下面是全部禁止 多个
  ignored-services: "*"
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**

info:
  app.name: chen-microcloud
  company.name: www.chen.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$


